---
# Must kill running firefox processes for profile to be correctly created
- name: Firefox | Kill running processes # noqa command-instead-of-shell no-changed-when
  ansible.builtin.shell: pkill -f firefox

- name: Create profiles
  firefox_profile:
    name: "{{ firefox_profile.key }}"
    path: "{{ firefox_home }}"
    state: present
  register: create_profile

- name: Install extensions
  firefox_addon:
    name: "{{ extension }}"
    profile_path: "{{ create_profile.profile_path }}"
    state: present
  with_items:
    - "{{ firefox_profile.value.extensions }}"
  loop_control:
    loop_var: extension

- name: Install user prefs
  ansible.builtin.lineinfile:
    path: "{{ create_profile.profile_path }}/prefs.js"
    create: true
    regexp: '^user_pref\("{{ pref.key }}",\s*\S+?\);\s*$'
    line: 'user_pref("{{ pref.key }}", {{ (''"%s"'' | format(pref.value)) if pref.value is string else (pref.value | lower) }});'
    mode: "0600"
  with_items: "{{ firefox_profile.value.preferences | default({}) | dict2items }}"
  loop_control:
    loop_var: pref
