---
firefox_profiles:
  default-release: # default fedora profile
    extensions:
      - bitwarden-password-manager
      - facebook-container
      - multi-account-containers
      - sponsorblock
      - ublock-origin
    preferences:
      browser.backspace_action: 0
