---
# defaults for pyenv
pyenv_init_shell: true
pyenv_version: "v2.3.18"
pyenv_virtualenv_version: "v1.2.1"
pyenv_python_versions:
  - 3.9.16
  - 3.11.3
pyenv_global: 3.11.3 system

# Firefox defaults
firefox_profiles:
  default-release: # default fedora profile
    extensions:
      - bitwarden-password-manager
      - facebook-container
      - multi-account-containers
      - sponsorblock
      - ublock-origin
    preferences:
    # values from https://github.com/arkenfox/user.js/blob/master/user.js
      browser.backspace_action: 0
      browser.aboutConfig.showWarning: false # disable about:config warning
      browser.startup.page: 0 # Set startup page - 0=blank, 1=home, 2=last visited page, 3=resume previous session
      browser.startup.homepage: "about:blank"
      browser.newtabpage.activity-stream.showSponsored: false # Pocket > Sponsored Stories
      browser.newtabpage.activity-stream.showSponsoredTopSites: false
      browser.newtabpage.activity-stream.default.sites: ""
      extensions.getAddons.showPane: false # disable recommendation pane in about:addons (uses Google Analytics)
      extensions.htmlaboutaddons.recommendations.enabled: false # disable recommendations in about:addons' Extensions and Themes panes [FF68+]
      datareporting.policy.dataSubmissionEnabled: false # disable new data submission [FF41+]
      datareporting.healthreport.uploadEnabled: false # [SETTING] Privacy & Security>Firefox Data Collection & Use>Allow Firefox to send technical... data
      # disable telemetry, The "unified" pref affects the behavior of the "enabled" pref
      # If "unified" is false then "enabled" controls the telemetry module
      # If "unified" is true then "enabled" only controls whether to record extended data
      # [NOTE] "toolkit.telemetry.enabled" is now LOCKED to reflect prerelease (true) or release builds (false) [2]
      # [1] https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html
      # [2] https://medium.com/georg-fritzsche/data-preference-changes-in-firefox-58-2d5df9c428b5 ***/
      toolkit.telemetry.unified: false
      toolkit.telemetry.enabled: false # see [NOTE]
      toolkit.telemetry.server: "data:,"
      toolkit.telemetry.archive.enabled: false
      toolkit.telemetry.newProfilePing.enabled: false
      toolkit.telemetry.shutdownPingSender.enabled: false
      toolkit.telemetry.updatePing.enabled: false
      toolkit.telemetry.bhrPing.enabled: false
      toolkit.telemetry.firstShutdownPing.enabled: false

      # disable Telemetry Coverage
      # [1] https://blog.mozilla.org/data/2018/08/20/effectively-measuring-search-in-firefox/ ***/
      toolkit.telemetry.coverage.opt-out: true
      toolkit.coverage.opt-out: true
      toolkit.coverage.endpoint.base: ""

      # disable PingCentre telemetry (used in several System Add-ons) [FF57+]
      # Defense-in-depth
      browser.ping-centre.telemetry: false
      # disable Firefox Home (Activity Stream) telemetry
      browser.newtabpage.activity-stream.feeds.telemetry: false
      browser.newtabpage.activity-stream.telemetry: false
      geo.enabled: 0
