- name: Flatpak | Add Flathub Repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Flatpak | Install Applications
  community.general.flatpak:
    name:
      - com.github.iwalton3.jellyfin-media-player
    state: present
