---
- name: Import VSCode rpm key
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode Repo
  ansible.builtin.yum_repository:
    name: code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    description: Visual Studio Code # actually name in file
    enabled: true
    file: vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  notify: Update DNF cache

- name: Install dnf apps
  ansible.builtin.dnf:
    name:
      - code
      - keepassxc
    state: present

- name: Install Google Chrome
  ansible.builtin.dnf:
    name: google-chrome
    enablerepo: config-manager
    state: present

- name: Download installers
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp
    mode: 0664
  with_items:
    - https://release.gitkraken.com/linux/gitkraken-amd64.rpm
    - https://kojipkgs.fedoraproject.org//packages/onedrive/2.4.21/1.fc37/x86_64/onedrive-2.4.21-1.fc37.x86_64.rpm

- name: Install rpm files
  ansible.builtin.dnf:
    name:
      - /tmp/gitkraken-amd64.rpm
      - /tmp/onedrive-2.4.21-1.fc37.x86_64.rpm
    disable_gpg_check: true
    state: present

- name: Install Jellyfin flatpak
  community.general.flatpak:
    name: com.github.iwalton3.jellyfin-media-player
    state: present
