---
- name: "Force Repo handlers to run"
  ansible.builtin.meta: flush_handlers

- name: Install dnf apps
  ansible.builtin.dnf:
    name:
      - code
      - google-chrome-stable
      - pre-commit
      - snapd
      - terraform
      - winehq-stable
    state: present

- name: Install dnf apps for pyenv
  ansible.builtin.dnf:
    name:
      - bzip2-devel
      - git # + for githooks
      - gcc
      - libffi-devel
      - openssl-devel
      - python3-tkinter
      - readline-devel
      - sqlite-devel
      - tk-devel
      - xz-devel
      - zlib-devel
    state: present

- name: Install pre-requirements to use RancherDesktop AppImage
  ansible.builtin.dnf:
    name:
      - pass
      - gnupg2
    state: present

- name: Enable Classic Snap Support
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

# need to logoff/logon for snaps to appear
- name: Install snap apps # TO-DO: this will fail as you first need to initialize system state, no idea how
  community.general.snap:
    name:
      - storage-explorer
      - snap-store

- name: Install flatpak
  community.general.flatpak:
    name:
      - com.axosoft.GitKraken
      - com.github.iwalton3.jellyfin-media-player
    state: present

- name: Remove KDE default installed apps
  ansible.builtin.dnf:
    name:
      - akregator
      - kf5-mailimporter
      - kaddressbook
      - kmail
      - kmail-account-wizard
      - kontact
      - konversation
      - korganizer
      - kwalletmanager
    autoremove: true
    state: absent
