---
- name: Setup Workstation
  hosts: localhost
  gather_facts: true
  become: true
  vars_files:
    - ./vars/default.yml
  roles:
    - role: setup
    - role: staticdev.pyenv
    - role: firefox
      vars:
        ansible_become: false # noqa var-naming[no-role-prefix]
