---
- name: Setup Workstation
  hosts: localhost
  gather_facts: true
  become: true
  vars_files:
    - ./vars/default.yml
  roles:
    - role: setup
      vars:
        - ansible_become: true
    - role: staticdev.firefox
      vars:
        - ansible_become: false
    - role: markosamuli.pyenv
      vars:
        - ansible_become: false
