---
roles:
  - src: staticdev.firefox
    version: 1.2.2
  - src: markosamuli.pyenv
    version: v6.2.0

collections:
  - name: community.general
    version: 6.1.0
    source: https://galaxy.ansible.com
